# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.1

os:
  - linux

dist: xenial

notifications:
  email: false

addons:
  apt:
      packages:
      - gnuplot5
